---
title: "Make publication table of the best stations"
output: 
  pdf_document: 
    fig_height: 8
---

v4 extracts its own lon/lats country and does so just for files that are big enough

```{r}
rm(list=ls())
library(xtable)
setwd("~/WORKSHOP/ESBJERG2/PUBLICATION")
df <- readRDS("OUTPUT/the_best.rds")
df2 <- df
#
```






# Round columns
```{r}
df2$longitude <- round(as.numeric(df2$longitude),2)
df2$latitude <- round(as.numeric(df2$latitude),2)
df2$beta1 <- round(df2$beta1,1)
df2 <- df2[, !names(df2) %in% c("AICbest", "BICbest")]
df2 <- df2[order(df2$country),]
```

# Write a latex sideways table
```{r}
df <- df2
df$country.1 <- NULL
cols <- colnames(df)
new_order <- append(
  cols[!cols %in% c("longitude", "latitude")],
  c("longitude", "latitude"),
  after = match("country", cols)
)
df <- df[, new_order]
# generate suitable station names
df$station_short <- tools::toTitleCase(gsub("_", " ", sub("-.*", "", sub("_annual$", "", df$filename))))


# select only some columns for the latex table
df_selected_small <- df[ , c("station_short", "country", "longitude", "latitude", "n_years",  "LRT_p", "beta1", "delta_AIC")]
df_selected_large <- df[ , c("station_short", "country", "longitude", "latitude", "n_years",  "LRT_p", "beta1", "delta_AIC", "delta_BIC")]


# Create LaTeX table with sidewaystable environment
xt_side <- xtable(df_selected_large, digits = c(0, 0, 0, 2, 2, 0, 5, 1, 3, 3))  # LRT_p = 5, beta1 = 3
latex_code <- print(
  xt_side,
  floating.environment = "sidewaystable",
  include.rownames = FALSE,
  print.results = FALSE
)

# Write sidewaystable to file
writeLines(c("\\documentclass{article}",
             "\\usepackage{rotating}",
             "\\begin{document}",
             latex_code,
             "\\end{document}"),
           "OUTPUT/sideways_table.tex")

# --------------------------
# Create normal LaTeX table
xt_reg <- xtable(df_selected_small, digits = c(0, 0, 0, 2, 2, 0, 5, 1, 1))  # same digit config
latex_code <- print(
  xt_reg,
  include.rownames = FALSE,
  print.results = FALSE
)

# Write regular table to file
writeLines(c("\\documentclass{article}",
             "\\begin{document}",
             latex_code,
             "\\end{document}"),
           "OUTPUT/regular_table.tex")



```

# make copies of the_best 3panel figures
```{r}
#system('rm -f FIGURES/THEBEST/*')
system('find FIGURES/THEBEST -mindepth 1 -delete')
for (i in 1:nrow(df))
{
  name <- paste0('FIGURES/',df$filename[i],'_3panel_bootstrap_beta1_baseR.png')
  cmd <- paste('cp ',name,' FIGURES/THEBEST/')
  system(cmd)
}
```





